### ISSUE TITLE
报错提示

### ISSUE THREAD

**Issue by seven-XINZ** [ltxhhz/koishi-plugin-imagify-skia#1]
![596b10861057a301bc3da8ae8c20a7c0](https://github.com/user-attachments/assets/cc916895-6eb9-4113-8e31-ba4598091d13)

**Comment by ltxhhz** [comment]
社区里有两个画布服务，是 canvas 和 skia 相互不兼容的，用这个

![QQ_1725867241444](https://github.com/user-attachments/assets/99b1c583-13f7-4663-82a7-5fa07a336f10)
